// API pública do motor 3D. O App importa só daqui.
export { SceneView } from './SceneView'
export type { SceneViewHandle, SceneViewProps, ViewPreset, Quality, Selection } from './types'
export type { Cutaway } from './Architecture'
export type { TimePreset } from './lighting/daylight'
export { TIME_PRESETS, formatTime } from './lighting/daylight'
export { CATALOG, MATERIAL_LIBRARY, materialsByCategory, resolveMaterial } from './materials/library'
export { catalogItems, catalogMoods, getCatalogItem } from './catalog/registry'
export { ObjectPreview } from './ObjectPreview'
export type { ObjectPreviewProps } from './ObjectPreview'
export { materialSwatch } from './materials/swatch'
export { PreviewPage, isPreviewUrl } from './dev/PreviewPage'
