import type { Catalog, CatalogItem, Material, MaterialCategory } from './schema'

/**
 * Catálogo embutido (reserva). O catálogo real vem de /assets/catalog.json + /assets/materials.json,
 * mantidos pela frente de Gráficos 3D; quando existir, ele substitui este em tempo de execução.
 */
const mat = (name: string, category: MaterialCategory, color: string, roughness: number, extra: Partial<Material> = {}): Material => ({ name, category, color: color as `#${string}`, roughness, ...extra })

export const FALLBACK_MATERIALS: Record<string, Material> = {
  'wood/smoked-oak': mat('Carvalho defumado', 'wood', '#6b4a32', 0.55, { texture: { set: 'wood-planks', tileSize: [1.2, 1.2] } }),
  'wood/walnut': mat('Nogueira', 'wood', '#7a4a2b', 0.5, { texture: { set: 'wood-grain', tileSize: [1, 1] } }),
  'wood/natural-oak': mat('Carvalho natural', 'wood', '#c79a64', 0.55, { texture: { set: 'wood-planks', tileSize: [1.2, 1.2] } }),
  'wood/ash': mat('Freijó claro', 'wood', '#d9b98a', 0.6, { texture: { set: 'wood-grain', tileSize: [1, 1] } }),
  'wood/ebony': mat('Ébano', 'wood', '#2b2420', 0.45, { texture: { set: 'wood-grain', tileSize: [1, 1] } }),
  'wood/deck-cumaru': mat('Deck de cumaru', 'wood', '#a9743f', 0.7, { texture: { set: 'wood-planks', tileSize: [1.5, 1.5] } }),
  'wood/cherry': mat('Cerejeira', 'wood', '#8d3f2a', 0.5, { texture: { set: 'wood-grain', tileSize: [1, 1] } }),
  'stone/marble-carrara': mat('Mármore Carrara', 'stone', '#ecebe8', 0.25),
  'stone/travertine': mat('Travertino', 'stone', '#d9c9a8', 0.6, { texture: { set: 'stone-tiles', tileSize: [0.6, 0.6] } }),
  'stone/slate': mat('Ardósia', 'stone', '#4a4f57', 0.7, { texture: { set: 'stone-tiles', tileSize: [0.6, 0.6] } }),
  'stone/granite-grey': mat('Granito cinza', 'stone', '#8b8d90', 0.4),
  'concrete/exposed': mat('Concreto aparente', 'concrete', '#9a9a96', 0.85),
  'ceramic/terracotta': mat('Terracota', 'ceramic', '#b9623d', 0.8, { texture: { set: 'stone-tiles', tileSize: [0.3, 0.3] } }),
  'ceramic/porcelain-white': mat('Porcelanato branco', 'ceramic', '#f1f1ef', 0.2, { texture: { set: 'stone-tiles', tileSize: [0.8, 0.8] } }),
  'fabric/linen': mat('Linho', 'fabric', '#e9e3d5', 0.95),
  'fabric/boucle': mat('Bouclé', 'fabric', '#f0ece4', 1),
  'fabric/grey-wool': mat('Lã cinza', 'fabric', '#a8aab0', 1),
  'fabric/oat-knit': mat('Tricô aveia', 'fabric', '#e6dcc6', 1),
  'fabric/navy-velvet': mat('Veludo azul-marinho', 'fabric', '#27407a', 0.9),
  'fabric/ochre-velvet': mat('Veludo ocre', 'fabric', '#e0a92f', 0.9),
  'fabric/rust-wool': mat('Lã ferrugem', 'fabric', '#d9693c', 1),
  'fabric/charcoal-felt': mat('Feltro grafite', 'fabric', '#3a3d44', 1),
  'leather/cognac': mat('Couro conhaque', 'leather', '#c2762e', 0.55),
  'paint/sand-limewash': mat('Cal areia', 'paint', '#e6dcc9', 0.95),
  'paint/white-matte': mat('Branco fosco', 'paint', '#f4f2ee', 0.9),
  'paint/exterior-white': mat('Branco externo', 'paint', '#f2f0ea', 0.9),
  'paint/warm-grey': mat('Cinza quente', 'paint', '#b9b4aa', 0.9),
  'paint/sage': mat('Verde sálvia', 'paint', '#9fae93', 0.9),
  'paint/terracotta': mat('Terracota suave', 'paint', '#cf8a68', 0.9),
  'paint/rust': mat('Ferrugem', 'paint', '#b4532a', 0.9),
  'paint/ink-blue': mat('Azul nanquim', 'paint', '#2a3b57', 0.9),
  'paint/mustard': mat('Mostarda', 'paint', '#d8a93a', 0.9),
  'paint/blush': mat('Rosa antigo', 'paint', '#e2b8ae', 0.9),
  'paint/charcoal': mat('Grafite', 'paint', '#34373d', 0.9),
  'ground/grass': mat('Gramado', 'ground', '#6a9a45', 1),
  'ground/gravel': mat('Cascalho', 'ground', '#b5ada0', 1),
  'ground/soil': mat('Terra de jardim', 'ground', '#5a4332', 1),
  'ground/asphalt': mat('Asfalto', 'ground', '#3b3d41', 0.95),
  'ground/sand': mat('Areia', 'ground', '#e2cf9f', 1),
  'water/pool': mat('Água de piscina', 'water', '#4cc0d8', 0.05, { opacity: 0.8 }),
  'metal/brushed-steel': mat('Aço escovado', 'metal', '#b4b8bd', 0.4, { metalness: 1 }),
  'metal/black-matte': mat('Metal preto fosco', 'metal', '#1d1f23', 0.6, { metalness: 0.8 }),
  'metal/brass': mat('Latão', 'metal', '#c9a05a', 0.35, { metalness: 1 }),
  'glass/clear': mat('Vidro', 'glass', '#cfe6ee', 0.05, { opacity: 0.3 }),
}

type D = [number, number, number]
const item = (id: string, name: string, category: CatalogItem['category'], dimensions: D, extra: Partial<CatalogItem> & { main?: string; accent?: string } = {}): CatalogItem => {
  const { main, accent, ...rest } = extra
  return {
    id,
    name,
    category,
    model: `models/${id}.glb`,
    dimensions: { width: dimensions[0], height: dimensions[1], depth: dimensions[2] },
    materialSlots: {
      main: { label: 'Estrutura', default: main ?? 'wood/walnut' },
      ...(accent ? { accent: { label: 'Estofado / detalhe', default: accent } } : {}),
    },
    ...rest,
  }
}

export const FALLBACK_ITEMS: CatalogItem[] = [
  item('sofa/three-seat', 'Sofá 3 lugares', 'sofa', [2.2, 0.85, 0.95], { accent: 'fabric/navy-velvet' }),
  item('sofa/modern-l', 'Sofá em L', 'sofa', [2.6, 0.85, 1.6], { accent: 'fabric/navy-velvet' }),
  item('sofa/two-seat', 'Sofá 2 lugares', 'sofa', [1.6, 0.85, 0.9], { accent: 'fabric/grey-wool' }),
  item('sofa/armchair', 'Poltrona', 'sofa', [0.8, 0.85, 0.85], { accent: 'leather/cognac' }),
  item('chair/dining-wood', 'Cadeira de jantar', 'chair', [0.45, 0.88, 0.5], { accent: 'fabric/rust-wool' }),
  item('chair/bar-stool', 'Banqueta alta', 'chair', [0.4, 0.75, 0.4], { main: 'metal/black-matte', accent: 'fabric/charcoal-felt' }),
  item('chair/office', 'Cadeira de escritório', 'chair', [0.62, 1.0, 0.62], { main: 'metal/black-matte', accent: 'fabric/charcoal-felt' }),
  item('table/dining-rect', 'Mesa de jantar 6 lugares', 'table', [1.8, 0.75, 0.9]),
  item('table/dining-round', 'Mesa redonda', 'table', [1.2, 0.75, 1.2], { main: 'wood/natural-oak' }),
  item('table/coffee-rect', 'Mesa de centro', 'table', [1.0, 0.4, 0.6]),
  item('table/coffee-round', 'Mesa de centro redonda', 'table', [0.9, 0.38, 0.9], { main: 'wood/natural-oak' }),
  item('table/side', 'Mesa lateral', 'table', [0.45, 0.5, 0.45]),
  item('desk/simple', 'Escrivaninha', 'desk', [1.4, 0.74, 0.7], { main: 'wood/ash', accent: 'metal/black-matte' }),
  item('bed/queen-modern', 'Cama queen', 'bed', [1.6, 1.0, 2.1], { accent: 'fabric/linen' }),
  item('bed/king', 'Cama king', 'bed', [1.93, 1.0, 2.1], { accent: 'fabric/linen' }),
  item('bed/single', 'Cama solteiro', 'bed', [0.9, 0.9, 2.0], { main: 'wood/natural-oak', accent: 'fabric/linen' }),
  item('storage/nightstand', 'Criado-mudo', 'storage', [0.45, 0.5, 0.4]),
  item('storage/wardrobe-2-door', 'Guarda-roupa', 'storage', [1.8, 2.3, 0.6], { main: 'wood/ash', accent: 'paint/white-matte' }),
  item('shelf/bookcase-tall', 'Estante', 'shelf', [0.9, 2.0, 0.35]),
  item('storage/sideboard', 'Aparador', 'storage', [1.6, 0.8, 0.45]),
  item('storage/tv-unit', 'Rack de TV', 'storage', [1.8, 0.5, 0.4], { main: 'wood/ash' }),
  item('shelf/wall-floating', 'Prateleira flutuante', 'shelf', [1.0, 0.04, 0.25], { mount: 'wall' }),
  item('lighting/floor-arc', 'Luminária de piso', 'lighting', [0.35, 1.6, 0.35], { main: 'metal/black-matte' }),
  item('lighting/table-lamp', 'Abajur', 'lighting', [0.3, 0.5, 0.3], { main: 'metal/brass', accent: 'fabric/linen', mount: 'surface' }),
  item('lighting/pendant-dome', 'Pendente', 'lighting', [0.45, 0.5, 0.45], { main: 'metal/brass', mount: 'ceiling' }),
  item('decor/art-frame', 'Quadro', 'decor', [0.7, 0.9, 0.04], { main: 'wood/ebony', accent: 'paint/terracotta', mount: 'wall' }),
  item('decor/mirror', 'Espelho', 'decor', [0.6, 1.5, 0.04], { main: 'metal/brass', accent: 'glass/clear', mount: 'wall' }),
  item('textile/curtain', 'Cortina', 'textile', [1.8, 2.5, 0.12], { main: 'fabric/linen', mount: 'wall' }),
  item('plant/monstera-large', 'Planta de vaso', 'plant', [0.5, 1.4, 0.5], { main: 'ceramic/terracotta', accent: 'ground/grass' }),
  item('plant/small-pot', 'Vaso pequeno', 'plant', [0.25, 0.4, 0.25], { main: 'ceramic/terracotta', accent: 'ground/grass' }),
  item('plant/tree-medium', 'Árvore média', 'plant', [3.0, 5.0, 3.0], { accent: 'ground/grass' }),
  item('plant/palm', 'Palmeira', 'plant', [1.6, 4.0, 1.6], { accent: 'ground/grass' }),
  item('plant/shrub', 'Arbusto', 'plant', [0.9, 0.9, 0.9], { main: 'ground/soil', accent: 'ground/grass' }),
  item('rug/rectangular', 'Tapete retangular', 'rug', [2.4, 0.015, 1.7], { main: 'fabric/oat-knit' }),
  item('rug/round', 'Tapete redondo', 'rug', [1.6, 0.015, 1.6], { main: 'fabric/oat-knit' }),
  item('kitchen/counter', 'Bancada de cozinha', 'kitchen', [2.0, 0.9, 0.6], { main: 'wood/ash', accent: 'stone/marble-carrara' }),
  item('kitchen/island', 'Ilha de cozinha', 'kitchen', [2.0, 0.92, 0.9], { accent: 'stone/marble-carrara' }),
  item('appliance/fridge', 'Geladeira', 'appliance', [0.7, 1.8, 0.75], { main: 'metal/brushed-steel' }),
  item('appliance/stove', 'Fogão', 'appliance', [0.6, 0.9, 0.6], { main: 'metal/brushed-steel' }),
  item('bathroom/toilet', 'Vaso sanitário', 'bathroom', [0.4, 0.4, 0.65], { main: 'ceramic/porcelain-white' }),
  item('bathroom/vanity', 'Gabinete com pia', 'bathroom', [0.8, 0.85, 0.5], { main: 'wood/ash', accent: 'stone/marble-carrara' }),
  item('bathroom/bathtub', 'Banheira', 'bathroom', [1.7, 0.55, 0.75], { main: 'ceramic/porcelain-white' }),
  item('bathroom/shower-box', 'Box de chuveiro', 'bathroom', [0.9, 2.0, 0.9], { main: 'glass/clear', accent: 'metal/brushed-steel' }),
  item('outdoor/sun-lounger', 'Espreguiçadeira', 'outdoor', [0.65, 0.4, 1.9], { main: 'wood/deck-cumaru', accent: 'fabric/linen' }),
  item('outdoor/table', 'Mesa externa', 'outdoor', [1.6, 0.75, 0.9], { main: 'wood/deck-cumaru' }),
  item('outdoor/bbq', 'Churrasqueira', 'outdoor', [1.2, 1.1, 0.6], { main: 'concrete/exposed', accent: 'metal/black-matte' }),
  item('outdoor/umbrella', 'Ombrelone', 'outdoor', [2.4, 2.4, 2.4], { main: 'wood/deck-cumaru', accent: 'fabric/linen' }),
  item('outdoor/car', 'Carro', 'outdoor', [1.85, 1.5, 4.5], { main: 'metal/black-matte' }),
  item('outdoor/mailbox', 'Caixa de correio', 'outdoor', [0.3, 1.2, 0.3], { main: 'metal/black-matte' }),
]

export const FALLBACK_CATALOG: Catalog = {
  format: 'design3d.catalog',
  version: '0.1.0',
  items: FALLBACK_ITEMS,
  materials: FALLBACK_MATERIALS,
}
